### ISSUE TITLE
Bedre tilpasset layout/design for mobil

### ISSUE THREAD

**Issue by Goddesen** [knowit/julekalender_frontend#17]
Den store julelys-lukevelgeren fungerer ikke helt på mobil. Kommentarfeltet er heller ikke fryktelig tilpasset. Trenger en del pirk her, kanskje en designer involvert? :)

**Comment by sverrejb** [comment]
Design er på plass, med mindre nokon meinar det bør endrast? Eg har ein påbegynt branch, men den må vel transplanterast over sidan git-historikken er endra.

**Comment by Goddesen** [comment]
Skal gå an å rebase din branch på ny historie tror jeg.
