### ISSUE TITLE
Forbedre bakgrunnsanimasjon

### ISSUE THREAD

**Issue by sverrejb** [knowit/julekalender_frontend#18]
Den animerte bakgrunnen brukar ein god del ressursar (under nokon nettlesarar og zoom-nivå). Den kan sikkert med fordel implementerast på ein meir optimal måte.

Kanskje en wasm eller anna webgl-løysing er vegen å gå?

**Comment by Goddesen** [comment]
Før:
<img width="495" alt="Screenshot 2021-09-01 at 19 27 17" src="https://user-images.githubusercontent.com/5515119/131716547-5f455044-bf3b-4a20-89dd-3dbde14c120d.png">

Nå:
<img width="490" alt="Screenshot 2021-09-01 at 19 26 22" src="https://user-images.githubusercontent.com/5515119/131716583-70ba262a-8516-41e3-b60f-50af63b9a48b.png">

**Comment by sverrejb** [comment]
Nice! HW = Hugo Wallenburg? :smile: 

Eg ser ikkje _kvar_ i koden du skrur på HW accel, men eg er også veldig trøtt.
