### ISSUE TITLE
Driftsmeldinger fra admin

### ISSUE THREAD

**Issue by sverrejb** [knowit/julekalender_frontend#21]
Sjølv om vi stort sett er flinke, hender det at det blir klabb og babb med feil i fasitt, uklarheit i oppgåvene osv. I desse tilfella hadde det vore fint med ein feed med "driftsmeldinger" eller noko.

**Comment by Goddesen** [comment]
bc12c2c2f0b39d445199e4df883b142145ed1285 legger til en liten animasjon dersom det er meldinger som gjelder systemet. Fortsatt TODO: Vise melding for spesifikk luke inne på luka.

**Comment by Goddesen** [comment]
Trenger noe enkelt admin-interface for å styre med driftsmeldinger.

**Comment by Goddesen** [comment]
Adminsider i eda312d41ec44ddea849104aef2c8db40326d564 og meldinger inne på luka i 2ec56a4a936cd201d252cd59162833b2cbb8125b. Tenker denne er good nå.
