### ISSUE TITLE
Småplukk

### ISSUE THREAD

**Issue by trgwii** [knowit/julekalender_frontend#37]
Hei, jeg ser nå at siden er live for i år, så her er småplukk:

1. Et bilde med 2020 vises dersom man linker til julekalenderen i sosiale medier.
2. HTML lang="en" selv om siden er på norsk - fører til at tastatur-input kommer på engelsk for min telefon.
3. Dark Reader extension fører til rare farger som gjør tittelen litt vrien å lese.
![IMG_20211129_213708_412](https://user-images.githubusercontent.com/11262022/143939623-5f823b8c-ca76-462c-b3a2-e0f411caa3c1.jpg)
![IMG_20211129_213712_317](https://user-images.githubusercontent.com/11262022/143939640-48609e59-3f94-482a-9af1-8b706f8fedd4.jpg)
![IMG_20211129_213922_892](https://user-images.githubusercontent.com/11262022/143939674-285b23e0-aad7-408c-898a-1ba720f6497f.jpg)

Jeg er kun på mobil i kveld, så unnskyld noe mangelfull rapport (manglende link til Dark Reader etc).

**Comment by Goddesen** [comment]
Damn, rekord for rask tilbakemelding. Takk! Første punkt fikser vi i skrivende stund, vi ser på resten ved anledning!

**Comment by trgwii** [comment]
Dark Reader issues fikses gjerne ved å slenge et par !important rundt omkring hvis det er interessant for dere å støtte det, men skjønner hvis det blir litt out of scope.

**Comment by Goddesen** [comment]
Ser at det varierer hvilke bokstaver som blir gjort mørke ut ifra skjermstørrelsen. For enkelte størrelser vises alt riktig, for andre vises bare halvparten av bokstavene. Skal vurdere å slenge på et lite utropstegn eller to, men det byr meg litt imot for å være ærlig. Kanskje lage en dark / low contrast mode...

**Comment by Goddesen** [comment]
Første to punktene fikset nå.

**Comment by trgwii** [comment]
Da anser jeg denne som løst, dere får tenke på dark mode :)

**Comment by trgwii** [comment]
Jeg vet forresten ikke om "nb" fungerer, min telefon dukker fortsatt opp med engelsk tastatur valgt og mulighet til å bytte til norsk i profil-innstillinger, men her på GitHub har jeg kun norsk tastatur.

**Comment by Goddesen** [comment]
Hmm det er siste gang jeg stoler på w3schools.

**Comment by trgwii** [comment]
![Screenshot_20211129-220803_Firefox Nightly](https://user-images.githubusercontent.com/11262022/143943386-aed0612c-f1b0-486a-8a0b-4880580357f6.jpg)
![Screenshot_20211129-220825_Firefox Nightly](https://user-images.githubusercontent.com/11262022/143943396-05e77aea-8fc0-4595-aabe-184378f47c51.jpg)

**Comment by trgwii** [comment]
interessant nok skjer det IKKE på brukernavn-feltet, men på alle andre input-felter... what

**Comment by trgwii** [comment]
Okay... glem den, MDN opererer forskjellig på forskjellige typer inputs... dette er vel bare noe udokumentert android-kompleksitet

**Comment by Goddesen** [comment]
Jeg har ikke samme problemet hos meg (safari iOS). Ser ut som norsk overalt, med  `.no` som autocomplete i e-postfeltet og slik.

**Comment by Goddesen** [comment]
Tror jeg lar denne ligge dersom ikke veldig mange kommer og klager :)

**Comment by Goddesen** [comment]
Kan prøve `no-nb` også forresten.
