### ISSUE TITLE
Glemt passord e-poster blir ikke sendt

### ISSUE THREAD

**Issue by trgwii** [knowit/julekalender_frontend#38]
Jeg har klart å opprette 2 brukere, med navn "TRGWII" og "TRGWII2" nå, jeg trodde jeg skrev epostadressen min feil på første forsøk, har forsøkt glemt passord på begge kontoene, men får ingen epost tilsendt meg selv.

**Comment by sverrejb** [comment]
Har du sjekka spam-filteret? Vi har hatt litt issues med at epost endar der.

**Comment by trgwii** [comment]
Ja, og søkt i alle mapper.

**Comment by Goddesen** [comment]
I loggene ser det kun ut som det er blitt bedt om nytt passord fra `TRGWII2`, og det skal også ha gått en e-post der. Om ikke loggene lyver 😄 . Helt sikker på at ingenting fant veien til spam?

**Comment by Goddesen** [comment]
Og jeg bekreftet nettopp med egen konto `@hey.com` at det skal fungere.

**Comment by trgwii** [comment]
Jaha, da er det vel Microsoft som ikke liker epostene deres. Så får jeg vel løse årets oppgaver fra TRGWII2 istedet ¯\_(ツ)_/¯

**Comment by Goddesen** [comment]
Æsj da. Kan undersøke om vi kan få e-postene til å se mer legitime ut for spamfilterne 🤖 . Om du slenger oss en e-post kan jeg overstyre passordet ditt manuelt.

**Comment by trgwii** [comment]
Hvem sender jeg til?

**Comment by Goddesen** [comment]
julekalender@knowit.no 🎅

**Comment by trgwii** [comment]
Da kan vi fortsette på mail sikkert, takk! :)
