### ISSUE TITLE
Redigering av kommentarer

### ISSUE THREAD

**Issue by Goddesen** [knowit/julekalender_frontend#6]
Brukere må få redigere kommentarer etter de er laget. I fjor var det mange som måtte kommentere på sine egne innlegg med oppdateringer, eller slette innlegget og prøve på nytt. Støtten skal allerede være på plass på backend.

**Comment by Ojself** [comment]
https://github.com/knowit/julekalender_frontend/pull/33

**Comment by Goddesen** [comment]
Helt på plass i 35976228202f8cb0de7d75adf238ab14ce449a4c
